# Generated by Django 5.1.3 on 2024-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_date', models.DateField()),
                ('student_time', models.CharField(max_length=100)),
                ('student_duration', models.CharField(max_length=100)),
                ('student_image', models.ImageField(upload_to='static/')),
                ('student_course', models.CharField(max_length=100)),
            ],
        ),
    ]
